### ISSUE TITLE
private package support

### ISSUE THREAD

**Issue by stonexer** [MagicCube/vscode-import-formatter#1]
https://github.com/MagicCube/vscode-import-formatter/blob/bb124ff00695ff7e745677c1f45e2b9f4aa37ff4/src/lexer.js#L1

```
import something from '@company/blala';
```

awesome project. thx!

**Comment by MagicCube** [comment]
哈哈哈，我竟然把@ali/xxxx给忘了，多谢

**Comment by MagicCube** [comment]
# 27fd8368a22d10911286b4c3e3553cf87dd02216

Fixed in v0.1.8
